### ISSUE TITLE
이미지의 태양 크기가 변함

### ISSUE THREAD

**Issue by seungwonpark** [guitar79/CenterAlign#1]
`2010-01-15-18-48-35_IMG_0643_DPP.JPG`부터 `2010-01-15-19-06-38_IMG_0689_DPP.JPG`까지 나타난 현상. 태양 크기가 변해버린다. (첨부 이미지 참조바람, 차례로 0643, 0663, 0686)

![2010-01-15-18-48-35_img_0643_dpp](https://cloud.githubusercontent.com/assets/13394294/24580026/e91f3c70-173b-11e7-94e2-4bca94d8f332.JPG)
![2010-01-15-18-57-58_img_0663_dpp](https://cloud.githubusercontent.com/assets/13394294/24580028/f0ee0904-173b-11e7-8d8d-0bf9a72ba90d.JPG)
![2010-01-15-19-05-38_img_0686_dpp](https://cloud.githubusercontent.com/assets/13394294/24580030/f5db7262-173b-11e7-8fdb-f30a8c3461b2.JPG)

원인을 파악하기 위해, 알고리즘을 더 살펴볼 필요가 있겠음.

**Comment by Kiehyun** [comment]
맞아~~
근데... 
sunrote.py 랑 sunscale.py 이놈을 이용해야 하는거 아닐까..??

**Comment by seungwonpark** [comment]
그러네요. `sunrot.py`와 `sunscale.py`를 사용해야 할 것 같습니다.
그냥 하나의 스크립트를 돌리면 3개의 과정이 모두 시행되는 스크립트를 짜놓으면 편할 것 같네요.
